/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_clean_testoutput;

public class Library {

    
    public boolean returnsFalse() {
        return false;
    }


    public boolean throwsExceptionIfTrueElseFalse(boolean value) {
	if (value) {
	    throw new IllegalArgumentException("Value is true!");
	}
        return false;
    }

}
